/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application.Views;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;

/**
 *
 * @author carlos
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    
    public MainView() {
        initComponents();
    }
    
    MouseAdapter mouseListener = new MouseAdapter() {
		public void mouseEntered(MouseEvent e) {	 
                    descricao.setText("Saldo");
		}
                public void mouseExited(MouseEvent e) {	 
                    descricao.setText(" ");
		}
    };
    
    MouseAdapter mouseListenerRed = new MouseAdapter() {
            
		public void mouseEntered(MouseEvent e) {	 
                    descricaoRed.setText("Dividas");
		}
                public void mouseExited(MouseEvent e) {	 
                    descricaoRed.setText(" ");
		}
                
    };
    
    MouseAdapter mouseListenerSuino = new MouseAdapter() {
        int a = 0;
		public void mouseEntered(MouseEvent e) {	 
                    economia.setText("Economias");
		}
                public void mouseExited(MouseEvent e) {	 
                    economia.setText(" ");
                    a = 0;
		}
                public void mouseClicked(MouseEvent e) {	 
                    a++;
                    if(a > 10) {
                        economia.setText("SUINO");
                    }
		}
    };
    
    MouseAdapter mouseListenerExtrato = new MouseAdapter() {
		public void mouseEntered(MouseEvent e) {	 
                    descricaoExtrato.setText("Extrato");
		}
                public void mouseExited(MouseEvent e) {	 
                    descricaoExtrato.setText(" ");
		}
    };
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        panelFundo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botaoMoney = new javax.swing.JButton();
        botaoMoney.addMouseListener(mouseListener);
        botaoMoney.setBorder(BorderFactory.createEmptyBorder());
        botaoMoney.setContentAreaFilled(false);
        botaoMoney.setFocusPainted(false);
        botaoMoneyRed = new javax.swing.JButton();
        botaoMoneyRed.addMouseListener(mouseListenerRed);
        botaoMoneyRed.setBorder(BorderFactory.createEmptyBorder());
        botaoMoneyRed.setContentAreaFilled(false);
        botaoMoneyRed.setFocusPainted(false);
        descricao = new javax.swing.JLabel();
        descricaoRed = new javax.swing.JLabel();
        botaoSuino = new javax.swing.JButton();
        botaoSuino.addMouseListener(mouseListenerSuino);
        botaoSuino.setBorder(BorderFactory.createEmptyBorder());
        botaoSuino.setContentAreaFilled(false);
        botaoSuino.setFocusPainted(false);
        economia = new javax.swing.JLabel();
        botaoExtrato = new javax.swing.JButton();
        botaoExtrato.addMouseListener(mouseListenerExtrato);
        botaoExtrato.setBorder(BorderFactory.createEmptyBorder());
        botaoExtrato.setContentAreaFilled(false);
        botaoExtrato.setFocusPainted(false);
        descricaoExtrato = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(null);
        setResizable(false);

        jDesktopPane1.setBackground(new java.awt.Color(0, 0, 0));
        jDesktopPane1.setMinimumSize(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setForeground(new java.awt.Color(0, 255, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/imagens/logo.png"))); // NOI18N

        botaoMoney.setBackground(new java.awt.Color(255, 255, 255));
        botaoMoney.setForeground(new java.awt.Color(255, 255, 255));
        botaoMoney.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/imagens/logo3moneypng.png"))); // NOI18N
        botaoMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMoneyActionPerformed(evt);
            }
        });

        botaoMoneyRed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/imagens/moneyRed.png"))); // NOI18N
        botaoMoneyRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMoneyRedActionPerformed(evt);
            }
        });

        descricao.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        descricao.setForeground(new java.awt.Color(255, 255, 255));
        descricao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descricao.setText(" ");

        descricaoRed.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        descricaoRed.setForeground(new java.awt.Color(255, 255, 255));
        descricaoRed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descricaoRed.setText(" ");

        botaoSuino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/imagens/suinoPequeno.png"))); // NOI18N
        botaoSuino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSuinoActionPerformed(evt);
            }
        });

        economia.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        economia.setForeground(new java.awt.Color(255, 255, 255));
        economia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        economia.setText(" ");

        botaoExtrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/imagens/extratoSuino.png"))); // NOI18N
        botaoExtrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExtratoActionPerformed(evt);
            }
        });

        descricaoExtrato.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        descricaoExtrato.setForeground(new java.awt.Color(255, 255, 255));
        descricaoExtrato.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descricaoExtrato.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(176, 176, 176))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(descricaoRed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(descricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoMoneyRed, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(botaoSuino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(economia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoExtrato, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(descricaoExtrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(287, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(botaoMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoMoneyRed, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descricaoRed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoSuino, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(economia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoExtrato, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descricaoExtrato)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelFundoLayout = new javax.swing.GroupLayout(panelFundo);
        panelFundo.setLayout(panelFundoLayout);
        panelFundoLayout.setHorizontalGroup(
            panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelFundoLayout.setVerticalGroup(
            panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 662, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMoneyActionPerformed
        new Saldo().setVisible(true);
    }//GEN-LAST:event_botaoMoneyActionPerformed

    private void botaoMoneyRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMoneyRedActionPerformed
        new Dividas().setVisible(true);
    }//GEN-LAST:event_botaoMoneyRedActionPerformed

    private void botaoExtratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExtratoActionPerformed
        new Extrato().setVisible(true);
    }//GEN-LAST:event_botaoExtratoActionPerformed

    private void botaoSuinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSuinoActionPerformed
        new Economia().setVisible(true);
    }//GEN-LAST:event_botaoSuinoActionPerformed

    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoExtrato;
    private javax.swing.JButton botaoMoney;
    private javax.swing.JButton botaoMoneyRed;
    private javax.swing.JButton botaoSuino;
    private javax.swing.JLabel descricao;
    private javax.swing.JLabel descricaoExtrato;
    private javax.swing.JLabel descricaoRed;
    private javax.swing.JLabel economia;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelFundo;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
